### ISSUE TITLE
responseHandler fails

### ISSUE THREAD

**Issue by jpa-akyos** [baptiste-dulac/SystempayBundle#13]
There is an issue on line 142 in this file https://github.com/baptiste-dulac/SystempayBundle/blob/master/src/Tlconseil/SystempayBundle/Service/SystemPay.php

```php
 $transaction = $this->findTransaction(request);
```
Just need to add $ before "request"

```php
 $transaction = $this->findTransaction($request);
```

**Comment by baptiste-dulac** [comment]
This was fixed on master.
